/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Agent
         * @description Register a new agent or get existing one.
         *
         *     **Example:**
         *     ```
         *     POST /agents?agent_id=research_001&name=Research Assistant&agent_type=research
         *     ```
         */
        post: operations["register_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Retrieve an agent by ID.
         *
         *     **Example:**
         *     ```
         *     GET /agents/research_001
         *     ```
         */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Stats
         * @description Get statistics about an agent's memory usage.
         *
         *     **Example:**
         *     ```
         *     GET /agents/research_001/stats
         *     ```
         *
         *     Returns:
         *         - total_memories: Total number of memories
         *         - average_importance: Average importance score
         *         - memory_types: Count by memory type
         *         - oldest_memory: Oldest memory timestamp
         *         - newest_memory: Newest memory timestamp
         */
        get: operations["get_agent_stats_agents__agent_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Memory
         * @description Add a new memory to the graph.
         *
         *     **Example:**
         *     ```
         *     POST /memories?agent_id=research_001&content=User prefers technical explanations&memory_type=preference&importance=0.8
         *     ```
         */
        post: operations["add_memory_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Retrieve a specific memory by ID.
         *
         *     **Example:**
         *     ```
         *     GET /memories/mem_abc123def456
         *     ```
         */
        get: operations["get_memory_memories__memory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/agent/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Memories
         * @description Get all memories for an agent.
         *
         *     **Example:**
         *     ```
         *     GET /memories/agent/research_001?limit=20&memory_types=fact,preference&time_range_days=30
         *     ```
         */
        get: operations["get_agent_memories_memories_agent__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Context
         * @description Retrieve relevant context for a query.
         *
         *     This is the core retrieval method agents use to get relevant past memories.
         *
         *     **Example:**
         *     ```
         *     POST /memories/retrieve?agent_id=research_001&query=What do I know about the user&limit=10&min_importance=0.5
         *     ```
         *
         *     Returns:
         *         - memories: List of relevant MemoryResponse objects
         *         - total_found: Total memories matching criteria
         *         - query: Echo of the query
         *         - retrieved_at: Timestamp
         */
        post: operations["retrieve_context_memories_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Context
         * @description Create a new context/session.
         *
         *     Contexts group related memories together (e.g., a conversation, research session).
         *
         *     **Example:**
         *     ```
         *     POST /contexts?name=Literature Review - Neural Networks&summary=Reviewing recent papers
         *     ```
         */
        post: operations["create_context_contexts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Relationship
         * @description Create a relationship between two memories.
         *
         *     **Example:**
         *     ```
         *     POST /relationships?from_memory_id=mem_abc&to_memory_id=mem_def&relation_type=supports&strength=0.8
         *     ```
         */
        post: operations["create_relationship_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relationships/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Related Memories
         * @description Get memories related to a given memory.
         *
         *     Traverses relationship graph to find connected memories.
         *
         *     **Example:**
         *     ```
         *     GET /relationships/mem_abc123?max_depth=2&min_strength=0.5
         *     ```
         */
        get: operations["get_related_memories_relationships__memory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sharing/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Memories
         * @description Share memories from one agent to another.
         *
         *     **Example:**
         *     ```
         *     POST /sharing/grant?from_agent_id=research_001&to_agent_id=writing_001&memory_ids=mem_abc,mem_def&permission=read
         *     ```
         *
         *     Returns:
         *         - shared_count: Number of memories successfully shared
         */
        post: operations["share_memories_sharing_grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sharing/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shared Memories
         * @description Get memories shared with an agent.
         *
         *     **Example:**
         *     ```
         *     GET /sharing/writing_001?limit=20
         *     ```
         */
        get: operations["get_shared_memories_sharing__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check if MemGraph API is operational.
         *
         *     Returns:
         *         Health status and service info
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint with API information.
         *
         *     Returns:
         *         API metadata and available endpoints
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Agent
         * @description Represents an AI agent that creates/uses memories.
         * @example {
         *       "id": "agent_abc123def456",
         *       "metadata": {
         *         "capabilities": [
         *           "search",
         *           "summarize"
         *         ],
         *         "version": "1.0"
         *       },
         *       "name": "Research Assistant",
         *       "type": "research"
         *     }
         */
        Agent: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /**
             * Type
             * @default general
             */
            type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * Context
         * @description Represents a conversation or task session.
         * @example {
         *       "id": "ctx_abc123def456",
         *       "metadata": {
         *         "duration_minutes": 45,
         *         "papers_reviewed": 5
         *       },
         *       "name": "Literature Review Session - Neural Networks",
         *       "summary": "Discussed recent advances in transformer architectures"
         *     }
         */
        Context: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Ended At */
            ended_at?: string | null;
            /** Summary */
            summary?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ContextResponse
         * @description Response containing retrieved context.
         */
        ContextResponse: {
            /** Memories */
            memories: components["schemas"]["MemoryResponse"][];
            /** Total Found */
            total_found: number;
            /** Query */
            query: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at?: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Memory
         * @description Represents a single memory unit in the graph.
         * @example {
         *       "content": "User prefers concise explanations with code examples",
         *       "id": "mem_abc123def456789",
         *       "importance": 0.8,
         *       "memory_type": "preference",
         *       "metadata": {
         *         "topic": "communication_style",
         *         "verified": true
         *       }
         *     }
         */
        Memory: {
            /** Id */
            id?: string;
            /** Content */
            content: string;
            /** @default fact */
            memory_type: components["schemas"]["MemoryType"];
            /**
             * Importance
             * @default 0.5
             */
            importance: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Embedding Id */
            embedding_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * MemoryRelationship
         * @description Represents a relationship between two memories.
         */
        MemoryRelationship: {
            /** From Memory Id */
            from_memory_id: string;
            /** To Memory Id */
            to_memory_id: string;
            type: components["schemas"]["RelationType"];
            /**
             * Strength
             * @default 0.5
             */
            strength: number;
            /** Reason */
            reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * MemoryResponse
         * @description Response containing memory data.
         */
        MemoryResponse: {
            memory: components["schemas"]["Memory"];
            /** Agent Name */
            agent_name?: string | null;
            /** Context Name */
            context_name?: string | null;
            /** Relevance Score */
            relevance_score?: number | null;
            /** Related Memories */
            related_memories?: string[];
        };
        /**
         * MemoryType
         * @description Types of memories that can be stored.
         * @enum {string}
         */
        MemoryType: "preference" | "fact" | "action" | "conversation" | "decision" | "observation";
        /**
         * RelationType
         * @description Types of relationships between memories.
         * @enum {string}
         */
        RelationType: "supports" | "contradicts" | "elaborates" | "follows" | "relates_to" | "supersedes";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_agent_agents_post: {
        parameters: {
            query: {
                /** @description Unique agent identifier */
                agent_id: string;
                /** @description Human-readable agent name */
                name: string;
                /** @description Type of agent (research, writing, coding, etc.) */
                agent_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_stats_agents__agent_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_memory_memories_post: {
        parameters: {
            query: {
                /** @description Agent ID */
                agent_id: string;
                /** @description Memory content */
                content: string;
                /** @description Type: preference, fact, action, conversation, decision, observation */
                memory_type?: string;
                /** @description Importance score 0.0-1.0 */
                importance?: number;
                /** @description Optional context/session ID */
                context_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_memories__memory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_memories_memories_agent__agent_id__get: {
        parameters: {
            query?: {
                /** @description Max memories to return */
                limit?: number;
                /** @description Comma-separated memory types to filter */
                memory_types?: string | null;
                /** @description Only return memories from last N days */
                time_range_days?: number | null;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_context_memories_retrieve_post: {
        parameters: {
            query: {
                /** @description Agent ID */
                agent_id: string;
                /** @description Natural language query */
                query: string;
                /** @description Max memories to return */
                limit?: number;
                /** @description Only recent memories (N days) */
                time_range_days?: number | null;
                /** @description Comma-separated memory types */
                memory_types?: string | null;
                /** @description Minimum importance threshold */
                min_importance?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_context_contexts_post: {
        parameters: {
            query: {
                /** @description Context name */
                name: string;
                /** @description Optional summary */
                summary?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Context"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_relationships_post: {
        parameters: {
            query: {
                /** @description Source memory ID */
                from_memory_id: string;
                /** @description Target memory ID */
                to_memory_id: string;
                /** @description Type: supports, contradicts, elaborates, follows, relates_to, supersedes */
                relation_type?: string;
                /** @description Relationship strength 0.0-1.0 */
                strength?: number;
                /** @description Optional explanation */
                reason?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRelationship"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_memories_relationships__memory_id__get: {
        parameters: {
            query?: {
                /** @description Max traversal depth */
                max_depth?: number;
                /** @description Minimum relationship strength */
                min_strength?: number;
            };
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_memories_sharing_grant_post: {
        parameters: {
            query: {
                /** @description Source agent ID */
                from_agent_id: string;
                /** @description Target agent ID */
                to_agent_id: string;
                /** @description Comma-separated memory IDs to share */
                memory_ids: string;
                /** @description Access permission: read or write */
                permission?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_memories_sharing__agent_id__get: {
        parameters: {
            query?: {
                /** @description Max memories to return */
                limit?: number;
            };
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
